name: AuthGuard
version: '${project.version}'
main: org.authguard.AuthGuard
api-version: '1.21'
author: TheNexoz/Juanserealpe
description: Secure authentication and registration plugin for modern Paper servers.
commands:
  register:
    description: Register a new account.
    usage: /register <password>
  login:
    description: Login to your account.
    usage: /login <password>
  setspawn:
    description: Set the spawn location for unauthenticated players.
    usage: /setspawn
    permission: authguard.spawn.manage
  delspawn:
    description: Delete the spawn location.
    usage: /delspawn
    permission: authguard.spawn.manage
permissions:
  authguard.admin:
    description: Allows administrative access to AuthGuard.
    default: op
  authguard.spawn.manage:
    description: Allows managing spawn locations.
    default: op

